version: '3.8'

services:
  whatsapp_agent:
    build: ./whatsapp_agent
    container_name: whatsapp_agent
    ports:
      - "8001:8001"

  ai_glossary:
    build: ./ai_glossary
    container_name: ai_glossary
    ports:
      - "8002:8002"

  automatic_translation:
    build: ./automatic_translation
    container_name: automatic_translation
    ports:
      - "8003:8003"

  skills_development:
    build: ./skills_development
    container_name: skills_development
    ports:
      - "8004:8004"

  ai_notekeeper:
    build: ./ai_notekeeper
    container_name: ai_notekeeper
    ports:
      - "8005:8005"

  shadowing:
    build: ./shadowing
    container_name: shadowing
    ports:
      - "8006:8006"